In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors
import requests
import io
import folium
import geopy
from geopy.geocoders import Nominatim

In [16]:
tables=pd.read_html("https://en.wikipedia.org/wiki/List_of_cities_in_Telangana_by_population")
tables=tables[0]
tables

,Rank,City,District,Type,Population (2011),Ref
0,1,Hyderabad,Hyderabad,Greater M.Corp,6993262,[2]
1,2,Warangal,Warangal Urban,Greater M.Corp,830281,[3][4]
2,3,Nizamabad,Nizamabad,M.Corp,311152,[2]
3,4,Khammam,Khammam,M.Corp,305000,[5]
4,5,Karimnagar,Karimnagar,M.Corp,289821,[2]
5,6,Ramagundam,Peddapalli,M.Corp,242979,[2]
6,7,Mahabubnagar,Mahabubnagar,M,222573,[6]
7,8,Nalgonda,Nalgonda,M,154326,[7][2]
8,9,Adilabad,Adilabad,M,117167,[8]
9,10,Siddipet,Siddipet,M,111358,[9]
10,11,Suryapet,Suryapet,M,106805,[2]
11,12,Miryalaguda,Nalgonda,M,104918,[2]

In [17]:
df_cities=tables.loc[:,['City','District']]
df_cities

            City        District
0      Hyderabad       Hyderabad
1       Warangal  Warangal Urban
2      Nizamabad       Nizamabad
3        Khammam         Khammam
4     Karimnagar      Karimnagar
5     Ramagundam      Peddapalli
6   Mahabubnagar    Mahabubnagar
7       Nalgonda        Nalgonda
8       Adilabad        Adilabad
9       Siddipet        Siddipet
10      Suryapet        Suryapet
11   Miryalaguda        Nalgonda

In [26]:
city_latitude=[]
city_longitude=[]

for i in df_cities.index:
    address = df_cities.loc[i,"City"]+", "+df_cities.loc[i,"District"]+", India"
    geolocator = Nominatim(user_agent="telangana_explorer")
    location = geolocator.geocode(address)
    city_latitude.append(location.latitude)
    city_longitude.append(location.longitude)

print(city_latitude)
print(city_longitude)

[17.3616079, 17.9806094, 18.6732693, 17.2465351, 18.4346438, 18.7615156, 16.745847599999998, 17.0504406, 19.6759452, 18.1017739, 17.15271675, 16.8709882]
[78.4746286, 79.5982115, 78.0978477, 80.1500326, 79.1322648, 79.4787848, 77.99366805028575, 79.2669235, 78.5339895, 78.8520128, 79.61976164399894, 79.5613977]

In [28]:
df_cities['Latitude']=city_latitude
df_cities

            City        District   Latitude
0      Hyderabad       Hyderabad  17.361608
1       Warangal  Warangal Urban  17.980609
2      Nizamabad       Nizamabad  18.673269
3        Khammam         Khammam  17.246535
4     Karimnagar      Karimnagar  18.434644
5     Ramagundam      Peddapalli  18.761516
6   Mahabubnagar    Mahabubnagar  16.745848
7       Nalgonda        Nalgonda  17.050441
8       Adilabad        Adilabad  19.675945
9       Siddipet        Siddipet  18.101774
10      Suryapet        Suryapet  17.152717
11   Miryalaguda        Nalgonda  16.870988

In [29]:
df_cities['Longitude']=city_longitude
df_cities

            City        District   Latitude  Longitude
0      Hyderabad       Hyderabad  17.361608  78.474629
1       Warangal  Warangal Urban  17.980609  79.598212
2      Nizamabad       Nizamabad  18.673269  78.097848
3        Khammam         Khammam  17.246535  80.150033
4     Karimnagar      Karimnagar  18.434644  79.132265
5     Ramagundam      Peddapalli  18.761516  79.478785
6   Mahabubnagar    Mahabubnagar  16.745848  77.993668
7       Nalgonda        Nalgonda  17.050441  79.266924
8       Adilabad        Adilabad  19.675945  78.533990
9       Siddipet        Siddipet  18.101774  78.852013
10      Suryapet        Suryapet  17.152717  79.619762
11   Miryalaguda        Nalgonda  16.870988  79.561398

In [34]:
telangana_lat=18.1124
telangana_lng=79.0193

map_telangana = folium.Map(location=[telangana_lat, telangana_lng], zoom_start=8)

for lat, lng, city, dis in zip(df_cities['Latitude'], df_cities['Longitude'], df_cities['City'],df_cities['District']):
    label='{}, {}'.format(city, dis)
    folium.Marker(
    location=[lat,lng],
    color="blue",
    popup=label
    ).add_to(map_telangana)

map_telangana

In [46]:
CLIENT_ID = '5B3DP3MB2VUYBXM1U5C0FRPFNKVNL1O1TAHNONMREM5RWOBP'
CLIENT_SECRET = 'WCEG545ZKN1NCDU2VTEWMPS023YC2LLJDUHQAPOMNFLRZAIN'
VERSION = '20180605'
LIMIT=100
RADIUS=100

import json

In [48]:
url='https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&ll={},{}&v={}&limit={}&radius={}'.format(CLIENT_ID,CLIENT_SECRET,df_cities.loc[0,"Latitude"],
                                                                                            df_cities.loc[0,"Longitude"],VERSION,LIMIT,RADIUS)

In [49]:
results=requests.get(url).json()
results

ConnectionError: HTTPSConnectionPool(host='api.foursquare.com', port=443): Max retries exceeded with url: /v2/venues/explore?&client_id=5B3DP3MB2VUYBXM1U5C0FRPFNKVNL1O1TAHNONMREM5RWOBP&client_secret=WCEG545ZKN1NCDU2VTEWMPS023YC2LLJDUHQAPOMNFLRZAIN&ll=17.3616079,78.4746286&v=20180605&limit=100&radius=100 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000218C9EB6BE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))